import React from 'react';

export default function Disclaimer() {
  return (
    <div className="disclaimer-text">
      <p><strong>Disclaimer:</strong> This response was generated by an AI using Retrieval-Augmented Generation (RAG) based on verified sources. Always consult a healthcare provider.</p>
    </div>
  );
}